---
title: "S416快速入门指南"
author: "Leabael"
date: "2022.8.31"
output: pdf_document
site: bookdown::bookdown_site
biblio-style: apa
link-citations: yes
documentclass: book
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 简介

本指南旨在帮助阅览者快速掌握S416实验室相关仪器操作，学习相关科研技能，培养良好科研习惯。

```{r eval=FALSE, include=FALSE}
bookdown::render_book("index.Rmd", 
  output_format="bookdown::gitbook", encoding="UTF-8")
bookdown::render_book("index.Rmd", 
  output_format="bookdown::pdf_book", encoding="UTF-8")
```

```{r eval=FALSE, include=FALSE}
gitbook(fig_caption = TRUE, number_sections = TRUE,
  self_contained = FALSE, anchor_sections = TRUE,
  lib_dir = "libs",
  global_numbering = !number_sections,
  pandoc_args = NULL, ..., template = "default",
  split_by = c("chapter", "chapter+number", "section", "section+number", "rmd", "none"),
  split_bib = TRUE, config = list(), table_css = TRUE)
```

```{r eval=FALSE, include=FALSE}
gitbook(fig_caption = TRUE, number_sections = TRUE,
  self_contained = FALSE, anchor_sections = TRUE,
  lib_dir = "libs",
  global_numbering = !number_sections,
  pandoc_args = NULL,
  template = "default",
  split_by = "none",
  split_bib = TRUE, config = list(), table_css = TRUE)
```
